### ISSUE TITLE
Concerning reg_tree.R

### ISSUE THREAD

**Issue by vijay-ratan** [andrebleier/cheapml#1]
Thanks for sharing your code (reg_tree.R), this helped me save some time. If I understand your code correctly, I think below line 69 you may want to insert the following line:

y <- this_data[, as.character(formula)[2]]

Otherwise I think the sse is not calculated correctly.
Thanks.

**Comment by andremonaco** [comment]
Hey, thanks I somehow did not see the issue. You are completely right. I fixed it in the new version. Thanks!
